/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsDebugTideApi {
    }
    interface DsTideChart {
    }
}
declare global {
    interface HTMLDsDebugTideApiElement extends Components.DsDebugTideApi, HTMLStencilElement {
    }
    var HTMLDsDebugTideApiElement: {
        prototype: HTMLDsDebugTideApiElement;
        new (): HTMLDsDebugTideApiElement;
    };
    interface HTMLDsTideChartElement extends Components.DsTideChart, HTMLStencilElement {
    }
    var HTMLDsTideChartElement: {
        prototype: HTMLDsTideChartElement;
        new (): HTMLDsTideChartElement;
    };
    interface HTMLElementTagNameMap {
        "ds-debug-tide-api": HTMLDsDebugTideApiElement;
        "ds-tide-chart": HTMLDsTideChartElement;
    }
}
declare namespace LocalJSX {
    interface DsDebugTideApi {
    }
    interface DsTideChart {
    }
    interface IntrinsicElements {
        "ds-debug-tide-api": DsDebugTideApi;
        "ds-tide-chart": DsTideChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-debug-tide-api": LocalJSX.DsDebugTideApi & JSXBase.HTMLAttributes<HTMLDsDebugTideApiElement>;
            "ds-tide-chart": LocalJSX.DsTideChart & JSXBase.HTMLAttributes<HTMLDsTideChartElement>;
        }
    }
}
